<template>
  <div id="app">
    <loading
      :active.sync="isLoading"
      class="animate__animated"
      :class="{ animate__fadeIn: isLoading === true, animate__fadeOut: isLoading === false}"
      style="animation-duration: .2s;"
    >
      <div class="loadingio-spinner-double-ring-fpu8dnlv067">
        <div class="ldio-cbtwt12ndh6">
          <div></div>
          <div></div>
          <div><div></div></div>
          <div><div></div></div>
        </div>
      </div>
    </loading>
    <AlertMessage></AlertMessage>
    <router-view />
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import AlertMessage from '@/components/AlertMessage';

export default {
  name: 'App',
  components: {
    AlertMessage
  },
  data() {
    return {};
  },

  computed: {
    ...mapGetters(['isLoading'])
  }
};
</script>

<style lang="scss">
@import './assets/scss/all.scss';
</style>

<style type="text/css">
@keyframes ldio-cbtwt12ndh6 {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-cbtwt12ndh6 div {
  box-sizing: border-box !important;
}
.ldio-cbtwt12ndh6 > div {
  position: absolute;
  width: 68px;
  height: 68px;
  top: 16px;
  left: 16px;
  border-radius: 50%;
  border: 4px solid #000;
  border-color: #404040 transparent #404040 transparent;
  animation: ldio-cbtwt12ndh6 1s linear infinite;
}

.ldio-cbtwt12ndh6 > div:nth-child(2),
.ldio-cbtwt12ndh6 > div:nth-child(4) {
  width: 58px;
  height: 58px;
  top: 21px;
  left: 21px;
  animation: ldio-cbtwt12ndh6 1s linear infinite reverse;
}
.ldio-cbtwt12ndh6 > div:nth-child(2) {
  border-color: transparent #f9f9f9 transparent #f9f9f9;
}
.ldio-cbtwt12ndh6 > div:nth-child(3) {
  border-color: transparent;
}
.ldio-cbtwt12ndh6 > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-cbtwt12ndh6 > div:nth-child(3) div:before,
.ldio-cbtwt12ndh6 > div:nth-child(3) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 4px;
  height: 4px;
  top: -4px;
  left: 28px;
  background: #404040;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #404040;
}
.ldio-cbtwt12ndh6 > div:nth-child(3) div:after {
  left: -4px;
  top: 28px;
  box-shadow: 64px 0 0 0 #404040;
}

.ldio-cbtwt12ndh6 > div:nth-child(4) {
  border-color: transparent;
}
.ldio-cbtwt12ndh6 > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-cbtwt12ndh6 > div:nth-child(4) div:before,
.ldio-cbtwt12ndh6 > div:nth-child(4) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 4px;
  height: 4px;
  top: -4px;
  left: 23px;
  background: #f9f9f9;
  border-radius: 50%;
  box-shadow: 0 54px 0 0 #f9f9f9;
}
.ldio-cbtwt12ndh6 > div:nth-child(4) div:after {
  left: -4px;
  top: 23px;
  box-shadow: 54px 0 0 0 #f9f9f9;
}
.loadingio-spinner-double-ring-fpu8dnlv067 {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-cbtwt12ndh6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-cbtwt12ndh6 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
